---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`4 + 4` equals `8`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`"4" + "4"` equals `"44"`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`4 + 4` equals `"44"`'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`"twen" + "ty"` equals `"twenty`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`True and False` equals `False`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`True and False` equals `0`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`5 >= 6` equals `False`"
  checked: true
name: A little of each kind
