---
locale: en
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: On the programming language _Cobra_.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: The British comedians _Monty Python_.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: In the snake bite suffered by the creator.
  checked: false
name: There is a snake in my code
